---
- name: CentOS - Import RPM-GPG-KEY-EPEL
  ansible.builtin.rpm_key:
    state: present
    key: "{{ signing_keys.epel[ansible_distribution_major_version].key }}"
    fingerprint: "{{ signing_keys.epel[ansible_distribution_major_version].fingerprint }}"
  register: rpm_key_epel

- name: CentOS - Install EPEL repository
  ansible.builtin.dnf:
    name:
      - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-\
        {{ ansible_distribution_major_version | int }}.noarch.rpm"
    state: present

- name: CentOS - rpm keys for Google
  ansible.builtin.import_tasks: system_redhat_rpm_keys_google.yml

- name: CentOS - Install zoom updater dependencies - curl
  ansible.builtin.dnf:
    name:
      - curl
    state: present
    allowerasing: true  # curl-minimal may already be installed

- name: CentOS - Install zoom updater dependencies
  ansible.builtin.dnf:
    name:
      - make
      - coreutils-single  # provides basename
      - createrepo_c
      - rpm
    state: present

- name: CentOS - install zoom updater service
  community.general.make:
    chdir: /opt/zoom-yum-repo
    target: install-service
  when:
    - stat_run_systemd.stat.exists
    - stat_run_systemd.stat.isdir

- name: CentOS - start zoom updater service
  community.general.make:
    chdir: /opt/zoom-yum-repo
    target: start-service
  when:
    - stat_run_systemd.stat.exists
    - stat_run_systemd.stat.isdir

### Version specific repositories
