---
# For user systemd
# https://www.freedesktop.org/software/systemd/man/file-hierarchy.html#Home%20Directory
- name: All - Create ~/.local/bin
  tags: [systemd]
  ansible.builtin.file:
    path: "$HOME/{{ item }}"
    state: directory
    mode: "0700"
  loop:
    - .local/bin
    - .local/lib
